### ISSUE TITLE
Stonks not working anymore

### ISSUE THREAD

**Issue by borisrunakov** [williamkray/maubot-ticker#5]
Trying with `!stonks tsla` returns :
```
pruned_json = resp_json['quoteResponse']['result'][0]
KeyError: 'quoteResponse'
```

**Comment by williamkray** [comment]
hmm, i'm not able to replicate this behavior... is this a fresh install?

**Comment by borisrunakov** [comment]
Yes I just installed, however I remember using the bot in the past in a
previous install.

**Comment by williamkray** [comment]
my money would be on a typo or other error in the config then... double check the API key you've entered for rapidAPI and make sure it's correct.

my api calls are succeeding, which means that the api itself hasn't changed how they return data or anything like that. the response you're getting isn't matching up with the expected structure, so it errors out. most often, the structure is different than expected because it's not authenticating properly or the call isn't being made right, rather than the api changing anything on their end.

**Comment by borisrunakov** [comment]
Trying with this from _apidojo_ works:
```
import http.client

conn = http.client.HTTPSConnection("yh-finance.p.rapidapi.com")

headers = {
    'x-rapidapi-host': "yh-finance.p.rapidapi.com",
    'x-rapidapi-key': "my_api_key"
    }

conn.request("GET", "/auto-complete?q=tesla&region=US", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
```
Maybe I am not using the correct API ?

**Comment by williamkray** [comment]
hmm. the bot is configured to connect to `apidojo-yahoo-finance-v1.p.rapidapi.com`, are you able to send queries to that hostname?

**Comment by borisrunakov** [comment]
> apidojo-yahoo-finance-v1.p.rapidapi.com

Using this I get : `{"message":"You are not subscribed to this API."}` 
How is the API called in RapidAPI HUB, so I can register myself ?
Currently I am using `YH Finance`:
![image](https://user-images.githubusercontent.com/93043305/151631041-b5a3add3-65a4-4839-b4d1-8cb99b4fb68d.png)

**Comment by williamkray** [comment]
I'm also using YH Finance. it seems like the host endpoint has changed, but maybe they're allowing old applications to use the old endpoint or something, which is why i'm not seeing the same issues.

this would be so much easier if yahoo published their api themselves instead of using this stupid apidojo service.

i will need to try and make it possible to set the host endpoint in the config file. no guarantees on time, but that seems like hopefully it would fix the issue for new configurations.

**Comment by borisrunakov** [comment]
That would be great! Thank you very much!

**Comment by borisrunakov** [comment]
There is also this https://www.yahoofinanceapi.com/

**Comment by williamkray** [comment]
quick status update, i tried just updating the host to point to the new endpoint, and it seems like the data structure that gets returned is all different. this will take me some time to find a free weekend and basically rewrite this unless someone else wants to do it. :cry:

**Comment by borisrunakov** [comment]
Thank you very much for the update @williamkray ! I will try if I find some time :(

**Comment by williamkray** [comment]
closed by https://github.com/williamkray/maubot-ticker/pull/6

**Comment by snex** [comment]
This is still broken.. There might be a hostname to make it work, but it is not given anywhere. The default one produces the error.
